id: P001681
initial_creation_type: ocr
created_at: 24/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W25243
  title: གངས་གྲོང་གི་རླུང་བུ
  author: ''
  volumes:
    bf64d62a0d6b41419bc4bac38e8d5d92:
      image_group_id: I5787
      title: ''
      volume_number: 1
      total_pages: 154
      base_file: v001.txt
